Add cops for trailing commas
alpinelab/codestyle pull request #16
Opened 2018-09-25 09:35 UTC by michaelbaudino

This commit adds 3 tightly-related cops to manage trailing commas in
lists (of method arguments and literals items).

* [Style/TrailingCommaInArguments](https://rubocop.readthedocs.io/en/latest/cops_style/#styletrailingcommainarguments):

    ```ruby
        # bad
    method(1, 2,)

    # good
    method(
      1, 2,
      3,
    )

    # good
    method(
      1,
      2,
    )
    ```

* [Style/TrailingCommaInArrayLiteral](https://rubocop.readthedocs.io/en/latest/cops_style/#styletrailingcommainarrayliteral):

    ```ruby
    # bad
    a = [1, 2,]

    # good
    a = [
      1, 2,
      3,
    ]

    # good
    a = [
      1,
      2,
    ]
    ```

* [Style/TrailingCommaInHashLiteral](https://rubocop.readthedocs.io/en/latest/cops_style/#styletrailingcommainhashliteral):

    ```ruby
    # bad
    a = { foo: 1, bar: 2, }

    # good
    a = {
      foo: 1, bar: 2,
      qux: 3,
    }

    # good
    a = {
      foo: 1,
      bar: 2,
    }
    ```

2018-09-25 09:36 UTC, michaelbaudino commented
The argument in favour of this cop is to avoid polluting git history on the last line of a list because we added an extra line (works when removing a line too).

2018-09-25 09:41 UTC, Polo2 approved these changes
Thanks JS good practices, mucher better for git blame

2018-09-25 10:01 UTC, ghost requested changes
I find this convention too much atypical, so I'd vote against.

2018-09-26 10:48 UTC, thibaultdalban approved these changes
I agree it's atypical but I saw it in multiple projects and I like the fact it reduces useless churn. Let's test it and we will see if it improves reviews or not.

2018-09-26 10:49 UTC, merged