Set enforcedStyle as compact
alpinelab/codestyle pull request #61
Opened 2018-10-12 09:20 UTC by Polo2

EnforcedStyle: nested (default)
```ruby
# good
# have each child on its own line
class Foo
  class Bar
  end
end
```
EnforcedStyle: compact : **PR Proposal**
```ruby
# good
# combine definitions as much as possible
class Foo::Bar
end
```

2018-10-12 12:24 UTC, ghost requested changes
.

2018-10-12 12:44 UTC, tjouan commented
On 2018-10-12 05:24:51 -0700, Thibault Jouan wrote:
> definition, "enforced style" and "compact" alone could apply no any other cop.

  I meant "to any other cop".

2018-10-12 13:31 UTC, Polo2 commented
Without this PR, `EnforcedStyle` is set by default to `nested` .
If both styles are acceptable,if we don't want our coding style should enforce one or the other, it seems that **the solution is to disable this cop**

2018-10-15 16:52 UTC, ghost requested changes
.

2018-10-16 16:54 UTC, ghost approved these changes

2023-02-17 15:25 UTC, closed without merging